ApexAcademyLearningToCode/main/default/objects/Coffee_Order__c/Coffee_Order__c.object-meta.xml
<CustomObject>
    <label>Coffee Order</label>
    <nameField>
        <displayFormat>CO-{0000}</displayFormat>
        <label>Coffee Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coffee Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ApexAcademyLearningToCode/main/default/objects/Coffee_Order__c/fields/Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Order_Total__c</fullName>
    <label>Order Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ApexAcademyLearningToCode/main/default/objects/Coffee_Order__c/fields/Received_Order_Total__c.field-meta.xml
<CustomField>
    <fullName>Received_Order_Total__c</fullName>
    <label>Received Order Total</label>
    <type>DateTime</type>
</CustomField>

ApexAcademyLearningToCode/main/default/classes/CoffeeOrderTriggerHandler.cls
public without sharing class CoffeeOrderTriggerHandler 
{
	public List<Coffee_Order__c> coffeeOrders;
	public List<Coffee_Order__c> oldCoffeeOrders;

	public CoffeeOrderTriggerHandler(){}

	public CoffeeOrderTriggerHandler(List<Coffee_Order__c> coffeeOrders,
		List<Coffee_Order__c> oldCoffeeOrders)
	{
		this.coffeeOrders = coffeeOrders;
		this.oldCoffeeOrders = oldCoffeeOrders;
	}

	public void run()
	{
		// Avoid running in the after context
		if (Trigger.isAfter != null && Trigger.isAfter)
		{
			return;
		}

		List<Coffee_Order__c> coffeeOrders = this.coffeeOrders;
		Integer coffeeOrdersSize = coffeeOrders.size();
		for (Integer i = 0, j = coffeeOrdersSize; i < j; i++)
		{
			Coffee_Order__c coffeeOrder = this.coffeeOrders[i];
			Coffee_Order__c oldCoffeeOrder = this.oldCoffeeOrders == null ? null : this.oldCoffeeOrders[i];
			coffeeOrder = this.receiveOrderTotal(coffeeOrder, oldCoffeeOrder);
		}
	}

	public Coffee_Order__c receiveOrderTotal(Coffee_Order__c coffeeOrder, 
		Coffee_Order__c oldCoffeeOrder)
	{
		// In the scenario of a record insert, oldCoffeeOrder will be null
		// because there is no old version of the record, so stub in an 
		// empty record to allow the below condition to evaluate correctly.
		if (oldCoffeeOrder == null)
			oldCoffeeOrder = new Coffee_Order__c();

		if (coffeeOrder.Received_Order_Total__c == null
			&& coffeeOrder.Order_Total__c != null
			&& oldCoffeeOrder.Order_Total__c == null)
		{
			coffeeOrder.Received_Order_Total__c = Datetime.now();
		}

		return coffeeOrder;
	}
}